"""change_status_column_to_varchar

Revision ID: 2959d9a9b146
Revises: 0001_initial_schema
Create Date: 2026-06-23 22:58:33.816594
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2959d9a9b146"
down_revision: str | None = "0001_initial_schema"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "agent_executions", "status", existing_type=sa.VARCHAR(length=20), server_default=None, existing_nullable=False
    )
    op.alter_column(
        "agent_executions", "input_tokens", existing_type=sa.INTEGER(), server_default=None, existing_nullable=False
    )
    op.alter_column(
        "agent_executions", "output_tokens", existing_type=sa.INTEGER(), server_default=None, existing_nullable=False
    )
    op.alter_column(
        "agent_executions", "duration_ms", existing_type=sa.INTEGER(), server_default=None, existing_nullable=False
    )
    op.alter_column(
        "project_artifacts", "revision", existing_type=sa.INTEGER(), server_default=None, existing_nullable=False
    )
    op.alter_column(
        "projects",
        "status",
        existing_type=postgresql.ENUM("pending", "running", "completed", "failed", "refining", name="project_status"),
        server_default=None,
        type_=sa.String(length=50),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "projects",
        "status",
        existing_type=sa.String(length=50),
        server_default=sa.text("'pending'::project_status"),
        type_=postgresql.ENUM("pending", "running", "completed", "failed", "refining", name="project_status"),
        existing_nullable=False,
    )
    op.alter_column(
        "project_artifacts",
        "revision",
        existing_type=sa.INTEGER(),
        server_default=sa.text("1"),
        existing_nullable=False,
    )
    op.alter_column(
        "agent_executions",
        "duration_ms",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        existing_nullable=False,
    )
    op.alter_column(
        "agent_executions",
        "output_tokens",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        existing_nullable=False,
    )
    op.alter_column(
        "agent_executions",
        "input_tokens",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        existing_nullable=False,
    )
    op.alter_column(
        "agent_executions",
        "status",
        existing_type=sa.VARCHAR(length=20),
        server_default=sa.text("'pending'::character varying"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
